[versions]
agp = "8.13.2"
kotlin = "2.2.21"
android-minSdk = "21"
android-compileSdk = "36"
vanniktechMavenPublish = "0.35.0"
coroutines = "1.10.2"
ktor = "3.3.3"
serialization = "1.9.0"
arrow = "2.2.0"
compose = "1.10.0"
datetime = "0.7.1"
desugar = "2.1.5"
shadow = "9.2.2"
airline = "0.9"
guava = "33.5.0-jre"
kotlinpoet = "2.2.0"
swagger-parser = "2.1.36"
gradle-publish = "2.0.0"
versions = "0.53.0"
slf4f = "2.0.17"
logback-android = "3.0.0"
logback-classic = "1.5.21"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-client-winhttp = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
compose-runtime-annotation = { module = "androidx.compose.runtime:runtime-annotation", version.ref = "compose" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
airline = { module = "io.airlift:airline", version.ref = "airline" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version.ref = "swagger-parser" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
lsf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4f" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logback-android" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }